---
'on':
  workflow_call:
    inputs:
      profile:
        required: true
        type: string
      # Parameters deciding which tests to run
      test-tari:
        required: true
        type: boolean
      test-wasm:
        # flag to run any wasm tests. Includes key manager
        required: true
        type: boolean

jobs:
  tests:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: ubuntu dependencies
        run: |
          sudo apt-get update
          sudo bash scripts/install_ubuntu_dependencies.sh

      - name: test key manager wasm
        if: ${{ inputs.test-wasm }}
        run: |
          npm install -g wasm-pack
          cd base_layer/key_manager
          rustup target add wasm32-unknown-unknown
          make test

      - name: Compile rust source code $${ inputs.profile }}
        run: |
          cargo test --no-run --locked --all-features ${{ inputs.profile }}

      - name: Run rust test suite $${ inputs.profile }}
        run: |
          cargo test -v --all-features ${{ inputs.profile }}
